package com.task.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

import oracle.bpel.services.workflow.task.model.ObjectFactory;
import oracle.bpel.services.workflow.task.model.Task;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://192.168.0.31:8103/integration/services/TaskService/TaskServicePort?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
  name="TaskService")
@XmlSeeAlso(
  { oracle.bpel.services.workflow.metadata.routingslip.model.ObjectFactory.class,
    ObjectFactory.class, oracle.bpel.services.workflow.common.model.ObjectFactory.class, com.task.services.types.ObjectFactory.class, oracle.bpel.services.workflow.common.tsc.model.ObjectFactory.class, oracle.bpel.services.workflow.evidence.model.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface TaskService
{
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/initiateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="initiateTaskResponse")
  public com.task.services.types.TaskServiceContextTaskBaseType initiateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="initiateTask")
    com.task.services.types.InitiateTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reinitiateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="reinitiateTaskResponse")
  public com.task.services.types.TaskServiceContextTaskBaseType reinitiateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reinitiateTask")
    com.task.services.types.InitiateTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlipInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlip/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlip/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/overrideRoutingSlipOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task overrideRoutingSlip(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="overrideRoutingSlip")
    com.task.services.types.OverrideRoutingSlipType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignmentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignment/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignment/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/skipCurrentAssignmentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task skipCurrentAssignment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="skipCurrentAssignment")
    com.task.services.types.TaskServiceContextTaskBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task updateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateTask")
    com.task.services.types.TaskServiceContextTaskBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/mergeAndUpdateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task mergeAndUpdateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="mergeAndUpdateTask")
    com.task.services.types.TaskServiceContextTaskBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/submitInfoForTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task submitInfoForTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="submitInfoForTask")
    com.task.services.types.TaskServiceContextTaskBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getUsersToRequestInfoForTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="listOfUserIds")
  public com.task.services.types.ListOfUserIdsType getUsersToRequestInfoForTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="getUsersToRequestInfoForTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipantsInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipants/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipants/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getFutureParticipantsOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/routingSlip",
    partName="payload", name="routingSlip")
  public oracle.bpel.services.workflow.metadata.routingslip.model.RoutingSlip getFutureParticipants(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="getFutureParticipants")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApproversInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApprovers/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApprovers/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/getApproversOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="listOfUserIds")
  public com.task.services.types.ListOfUserIdsType getApprovers(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="getApprovers")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task escalateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="escalateTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/escalateTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean escalateTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="escalateTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task withdrawTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="withdrawTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/withdrawTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean withdrawTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="withdrawTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task suspendTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="suspendTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean suspendTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="suspendTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task resumeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="resumeTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean resumeTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="resumeTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task acquireTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="acquireTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/acquireTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean acquireTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="acquireTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task releaseTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="releaseTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/releaseTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean releaseTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="releaseTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task reassignTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reassignTask")
    com.task.services.types.ReassignTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reassignTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean reassignTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reassignTasks")
    com.task.services.types.ReassignTasksType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/routeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task routeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="routeTask")
    com.task.services.types.RouteTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/pushBackTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task pushBackTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="pushBackTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task delegateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="delegateTask")
    com.task.services.types.DelegateTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/delegateTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean delegateTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="delegateTasks")
    com.task.services.types.DelegateTasksType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/errorTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task errorTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="errorTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addComment/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addComment/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task addComment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addComment")
    com.task.services.types.AddCommentType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addCommentToTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean addCommentToTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addCommentToTasks")
    com.task.services.types.AddCommentToTasks payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachmentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachment/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachment/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addAttachmentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task addAttachment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addAttachment")
    com.task.services.types.AddAttachmentType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachmentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachment/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachment/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeAttachmentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task removeAttachment(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="removeAttachment")
    com.task.services.types.RemoveAttachmentType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocumentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocument/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocument/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/addDocumentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task addDocument(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="addDocument")
    com.task.services.types.AddDocumentType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocumentInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocument/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocument/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/removeDocumentOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task removeDocument(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="removeDocument")
    com.task.services.types.RemoveDocumentType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/renewTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task renewTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="renewTask")
    com.task.services.types.RenewTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcome/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcome/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task updateTaskOutcome(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateTaskOutcome")
    com.task.services.types.UpdateTaskOutcomeType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateOutcomeOfTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean updateOutcomeOfTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateOutcomeOfTasks")
    com.task.services.types.UpdateOutcomeOfTasks payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRouteInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRoute/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRoute/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updateTaskOutcomeAndRouteOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task updateTaskOutcomeAndRoute(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updateTaskOutcomeAndRoute")
    com.task.services.types.UpdateTaskOutcomeAndRouteType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task requestInfoForTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="requestInfoForTask")
    com.task.services.types.RequestInfoForTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapprovalInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapproval/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapproval/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/requestInfoForTaskWithReapprovalOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task requestInfoForTaskWithReapproval(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="requestInfoForTaskWithReapproval")
    com.task.services.types.RequestInfoForTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/createToDoTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task createToDoTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="createToDoTask")
    com.task.services.types.CreateToDoTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task deleteTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="deleteTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/deleteTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean deleteTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="deleteTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="purgeTaskOutput")
  public boolean purgeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="purgeTask")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/purgeTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="bulkOperationOutput")
  public boolean purgeTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="purgeTasks")
    com.task.services.types.TaskIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChangesInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChanges/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChanges/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/setTaskSequenceChangesOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="setTaskSequenceChangesOutput")
  public int setTaskSequenceChanges(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="setTaskSequenceChanges")
    com.task.services.types.SetTaskSequenceChangesType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/restartRootTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="initiateTaskResponse")
  public com.task.services.types.TaskServiceContextTaskBaseType restartRootTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="restartRootTask")
    com.task.services.types.RestartRootTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/prepareForRestartRootTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task prepareForRestartRootTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="prepareForRestartRootTask")
    com.task.services.types.RestartRootTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/reevaluateTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="reevaluateTaskOutput")
  public boolean reevaluateTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="reevaluateTask")
    com.task.services.types.ReevaluateTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriority/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriority/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String updatePriority(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updatePriority")
    com.task.services.types.PriorityIdsType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasks/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasks/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/updatePriorityOfTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String updatePriorityOfTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="updatePriorityOfTasks")
    com.task.services.types.PriorityIdsListType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimersInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimers/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimers/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/suspendTimersOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String suspendTimers(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="suspendTimers")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimersInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimers/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimers/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/resumeTimersOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
    partName="payload", name="successResponseOutput")
  public String resumeTimers(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="resumeTimers")
    com.task.services.types.TaskServiceContextTaskTaskIdBaseType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTaskInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTask/Fault/operationErroredFault",
          className=com.task.services.WorkflowErrorMessage.class),
        @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTask/Fault/staleObjectFault",
          className=com.task.services.StaleObjectFaultMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskService/TaskService/decomposeTaskOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public Task decomposeTask(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskService",
      partName="payload", name="decomposeTask")
    com.task.services.types.DecomposeTaskType payload)
    throws com.task.services.WorkflowErrorMessage, com.task.services.StaleObjectFaultMessage;
}
