package com.taskQuery.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://192.168.0.31:8103/integration/services/TaskQueryService/TaskQueryService?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
  name="TaskQueryService")
@XmlSeeAlso(
  { oracle.bpel.services.workflow.task.error.model.ObjectFactory.class, oracle.bpel.services.workflow.task.model.ObjectFactory.class, oracle.bpel.services.workflow.common.model.ObjectFactory.class, oracle.bpel.services.workflow.query.model.ObjectFactory.class, oracle.bpel.services.workflow.common.tsc.model.ObjectFactory.class, oracle.bpel.services.workflow.user.model.ObjectFactory.class, oracle.bpel.services.workflow.evidence.model.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface TaskQueryService
{
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/authenticateInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/authenticate/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/authenticateOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/common",
    partName="payload", name="workflowContext")
  public oracle.bpel.services.workflow.common.model.WorkflowContextType authenticate(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/common",
      partName="payload", name="credential")
    oracle.bpel.services.workflow.common.model.CredentialType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/authenticateOnBehalfOfInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/authenticateOnBehalfOf/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/authenticateOnBehalfOfOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/common",
    partName="payload", name="workflowContext")
  public oracle.bpel.services.workflow.common.model.WorkflowContextType authenticateOnBehalfOf(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="credentialOnBehalfOfRequest")
    oracle.bpel.services.workflow.query.model.CredentialOnBehalfOfRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getWorkflowContextInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getWorkflowContext/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getWorkflowContextOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/common",
    partName="payload", name="workflowContext")
  public oracle.bpel.services.workflow.common.model.WorkflowContextType getWorkflowContext(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="workflowContextRequest")
    oracle.bpel.services.workflow.query.model.WorkflowContextRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/destroyContextInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/destroyWorkflowContext/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/destroyContextOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="successResponse")
  public String destroyWorkflowContext(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/common",
      partName="payload", name="workflowContext")
    oracle.bpel.services.workflow.common.model.WorkflowContextType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/refreshWorkflowContextInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/refreshWorkflowContext/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/refreshWorkflowContextOutput")
  public void refreshWorkflowContext(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/common",
      partName="payload", name="workflowContext", mode=Mode.INOUT)
    Holder<oracle.bpel.services.workflow.common.model.WorkflowContextType> payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/updateWorkflowContextInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/updateWorkflowContext/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/updateWorkflowContextOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/common",
    partName="payload", name="workflowContext")
  public oracle.bpel.services.workflow.common.model.WorkflowContextType updateWorkflowContext(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="updateWorkflowContextRequest")
    oracle.bpel.services.workflow.query.model.UpdateWorkflowContextRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskListResponse")
  public oracle.bpel.services.workflow.query.model.TaskListResponseType queryTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="taskListRequest")
    oracle.bpel.services.workflow.query.model.TaskListRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryAggregatedTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryAggregatedTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryAggregatedTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="aggregatedTasksResponse")
  public oracle.bpel.services.workflow.query.model.AggregatedTasksResponseType queryAggregatedTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="queryAggregatedTasksRequest")
    oracle.bpel.services.workflow.query.model.QueryAggregatedTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/countTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/countTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/countTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskCountResponse")
  public int countTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="countTasksRequest")
    oracle.bpel.services.workflow.query.model.CountTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/doesTaskExistInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/doesTaskExist/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/doesTaskExistOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskExistsResponse")
  public boolean doesTaskExist(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="doesTaskExistRequest")
    oracle.bpel.services.workflow.query.model.CountTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryViewTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryViewTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryViewTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskListResponse")
  public oracle.bpel.services.workflow.query.model.TaskListResponseType queryViewTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="queryViewTasksRequest")
    oracle.bpel.services.workflow.query.model.QueryViewTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryViewAggregatedTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryViewAggregatedTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryViewAggregatedTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="aggregatedTasksResponse")
  public oracle.bpel.services.workflow.query.model.AggregatedTasksResponseType queryViewAggregatedTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="queryViewAggregatedTasksRequest")
    oracle.bpel.services.workflow.query.model.QueryViewAggregatedTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/countViewTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/countViewTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/countViewTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskCountResponse")
  public int countViewTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="countViewTasksRequest")
    oracle.bpel.services.workflow.query.model.CountViewTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/doesViewTaskExistInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/doesViewTaskExist/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/doesViewTaskExistOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskExistsResponse")
  public boolean doesViewTaskExist(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="doesViewTaskExistRequest")
    oracle.bpel.services.workflow.query.model.CountViewTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryDecomposedTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryDecomposedTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryDecomposedTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskListResponse")
  public oracle.bpel.services.workflow.query.model.TaskListResponseType queryDecomposedTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="queryDecomposedTasksRequest")
    oracle.bpel.services.workflow.query.model.QueryDecomposedTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryTaskErrorsInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryTaskErrors/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/queryTaskErrorsOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskErrorsResponse")
  public oracle.bpel.services.workflow.query.model.TaskErrorsResponseType queryTaskErrors(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="queryTaskErrorsRequest")
    oracle.bpel.services.workflow.query.model.QueryTaskErrorsRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskHistoryInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskHistory/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskHistoryOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskListResponse")
  public oracle.bpel.services.workflow.query.model.TaskListResponseType getTaskHistory(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="taskHistoryRequest")
    oracle.bpel.services.workflow.query.model.TaskHistoryRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskDetailsByIdInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskDetailsById/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskDetailsByIdOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public oracle.bpel.services.workflow.task.model.Task getTaskDetailsById(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="taskDetailsByIdRequest")
    oracle.bpel.services.workflow.query.model.TaskDetailsByIdRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskDetailsByNumberInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskDetailsByNumber/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskDetailsByNumberOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public oracle.bpel.services.workflow.task.model.Task getTaskDetailsByNumber(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="taskDetailsByNumberRequest")
    oracle.bpel.services.workflow.query.model.TaskDetailsByNumberRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskVersionDetailsInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskVersionDetails/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskVersionDetailsOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/task",
    partName="payload", name="task")
  public oracle.bpel.services.workflow.task.model.Task getTaskVersionDetails(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="taskVersionDetailsRequest")
    oracle.bpel.services.workflow.query.model.TaskVersionDetailsRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getPermittedAssigneesInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getPermittedAssignees/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getPermittedAssigneesOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="getPermittedAssigneesResponse")
  public oracle.bpel.services.workflow.query.model.GetPermittedAssigneesResponseType getPermittedAssignees(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="getPermittedAssigneesRequest")
    oracle.bpel.services.workflow.query.model.GetPermittedAssigneesRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getPermittedAssigneesForTasksInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getPermittedAssigneesForTasks/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getPermittedAssigneesForTasksOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="getPermittedAssigneesForTasksResponse")
  public oracle.bpel.services.workflow.query.model.GetPermittedAssigneesForTasksResponseType getPermittedAssigneesForTasks(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="getPermittedAssigneesForTasksRequest")
    oracle.bpel.services.workflow.query.model.GetPermittedAssigneesForTasksRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskSequenceInput", fault =
      { @FaultAction(value="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskSequence/Fault/processingErrorFault",
          className=com.taskQuery.services.WorkflowErrorMessage.class) },
    output="http://xmlns.oracle.com/bpel/workflow/taskQueryService/TaskQueryService/getTaskSequenceOutput")
  @WebResult(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
    partName="payload", name="taskSequence")
  public oracle.bpel.services.workflow.query.model.TaskSequenceType getTaskSequence(@WebParam(targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
      partName="payload", name="getTaskSequenceRequest")
    oracle.bpel.services.workflow.query.model.GetTaskSequenceRequestType payload)
    throws com.taskQuery.services.WorkflowErrorMessage;
}
