package com.taskQuery.services;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://192.168.0.31:8103/integration/services/TaskQueryService/TaskQueryService?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
  name="TaskQueryService")
public class TaskQueryService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.taskQuery.services.TaskQueryService_Service");
      URL baseUrl = TaskQueryService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            TaskQueryService_Service.class.getResource("http://192.168.0.31:8103/integration/services/TaskQueryService/TaskQueryService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://192.168.0.31:8103/integration/services/TaskQueryService/TaskQueryService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://192.168.0.31:8103/integration/services/TaskQueryService/TaskQueryService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://192.168.0.31:8103/integration/services/TaskQueryService/TaskQueryService?WSDL",
          e);
    }
  }

  public TaskQueryService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/bpel/workflow/taskQueryService",
                    "TaskQueryService"));
  }

  public TaskQueryService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="TaskQueryServicePortSAML")
  public com.taskQuery.services.TaskQueryService getTaskQueryServicePortSAML()
  {
    return (com.taskQuery.services.TaskQueryService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskQueryService",
                                                                             "TaskQueryServicePortSAML"),
                                                                   com.taskQuery.services.TaskQueryService.class);
  }

  @WebEndpoint(name="TaskQueryServicePortSAML")
  public com.taskQuery.services.TaskQueryService getTaskQueryServicePortSAML(WebServiceFeature... features)
  {
    return (com.taskQuery.services.TaskQueryService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskQueryService",
                                                                             "TaskQueryServicePortSAML"),
                                                                   com.taskQuery.services.TaskQueryService.class,
                                                                   features);
  }

  @WebEndpoint(name="TaskQueryServicePort")
  public com.taskQuery.services.TaskQueryService getTaskQueryServicePort()
  {
    return (com.taskQuery.services.TaskQueryService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskQueryService",
                                                                             "TaskQueryServicePort"),
                                                                   com.taskQuery.services.TaskQueryService.class);
  }

  @WebEndpoint(name="TaskQueryServicePort")
  public com.taskQuery.services.TaskQueryService getTaskQueryServicePort(WebServiceFeature... features)
  {
    return (com.taskQuery.services.TaskQueryService) super.getPort(new QName("http://xmlns.oracle.com/bpel/workflow/taskQueryService",
                                                                             "TaskQueryServicePort"),
                                                                   com.taskQuery.services.TaskQueryService.class,
                                                                   features);
  }
}
