package com.taskQuery.services;

import javax.xml.ws.WebFault;

@WebFault(faultBean="oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType",
  targetNamespace="http://xmlns.oracle.com/bpel/workflow/taskQueryService",
  name="taskQueryServiceFaultResponse")
public class WorkflowErrorMessage
  extends Exception
{
  private oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType faultInfo;

  public WorkflowErrorMessage(String message,
                              oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public WorkflowErrorMessage(String message,
                              oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType faultInfo,
                              Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(oracle.bpel.services.workflow.query.model.TaskQueryServiceFaultType faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
