package com.process.services;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://192.168.0.31:8103/soa-infra/services/default/testBPM/TestProcess.service?WSDL",
  targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/TestProcess",
  name="TestProcessPortType")
@XmlSeeAlso(
  { com.mgear.services.types.ObjectFactory.class })
public interface TestProcessPortType
{
  @WebMethod(action="start")
  @Action(input="start")
  @RequestWrapper(localName="start", targetNamespace="http://xmlns.oracle.com/bpmn/bpmnProcess/TestProcess",
    className="com.mgear.services.types.Start")
  @Oneway
  public void start(@WebParam(targetNamespace="", name="data")
    String data, @WebParam(targetNamespace="", name="user")
    String user);
}
